version: '3'

services:
    nginx:
        image: nginx:1.13-alpine
        ports:
            - "8080:80"
        volumes:
            - ./vktask.conf:/etc/nginx/conf.d/default.conf
    php:
        build: ./php_build
        volumes:
            - ./backend/src:/code
    mysql:
        image: mariadb:10.2
        volumes:
            - mysqldata:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=UcLio
            - MYSQL_DATABASE=vktask
            - MYSQL_USER=vk
            - MYSQL_PASSWORD=6IK4l
volumes:
    mysqldata:
