version: '3'

services:
    nginx:
        image: nginx:1.13-alpine
        ports:
            - "8080:80"
        volumes:
            - ./vktask.conf:/etc/nginx/conf.d/default.conf
    php:
        image: php:5.6-fpm-alpine
        volumes:
            - ./backend/src:/code
